PostgreSQL:
  image: postgres:12.0-alpine
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - POSTGRES_DB=trip-db
  volumes:
    - ./src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql
